name: "fixtures_default"
version: 1.0.0
client:
#这个必须是在organization内定义的组织，在sdk中string也是这个
  organization: orgmai
  logging:
    level: info
  cryptoconfig:
    path: ${GOPATH}/src/github.com/test.com/test/fixtures/crypto-config
  credentialStore:
    path: /tmp/test-store
    cryptoStore:
      path: /tmp/test-msp
  BCCSP:
    security:
     enabled: true
     default:
      provider: "SW"
     hashAlgorithm: "SHA2"
     softVerify: true
     level: 256
  tlsCerts:
    systemCertPool: false

    client:
      key:
        path:
      cert:
        path:

channels:
  mychannel:
    peers:
      peer0.orgmai.test.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.orgmai.test.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      discovery:
        maxTargets: 2
        retryOpts:
          attempts: 4
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
      eventService:
        resolverStrategy: PreferOrg
        balancer: Random
        blockHeightLagThreshold: 5
        reconnectBlockHeightLagThreshold: 10
        peerMonitorPeriod: 5s


organizations:
  orgmai:
    mspid: OrgMaiMSP
    cryptoPath: peerOrganizations/orgmai.test.com/users/{userName}@orgmai.test.com/msp
    peers:
      - peer0.orgmai.test.com
      - peer1.orgmai.test.com
    certificateAuthorities:
      - ca.orgmai.test.com
  ordererorg:
    mspID: "OrdererMSP"
    cryptoPath: ordererOrganizations/test.com/users/{username}@test.com/msp
orderers:
  orderer.test.com:
    url: localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.test.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/test.com/test/fixtures/crypto-config/ordererOrganizations/test.com/tlsca/tlsca.test.com-cert.pem

peers:
 peer0.orgmai.test.com:
    url: localhost:7051
    eventUrl: localhost:7053
    grpcOptions:
      ssl-target-name-override: peer0.orgmai.test.com
      keep-alive-time: 0s
      keep-alive-timeout: 50s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/test.com/test/fixtures/crypto-config/peerOrganizations/orgmai.test.com/tlsca/tlsca.orgmai.test.com-cert.pem
 peer1.orgmai.test.com:
    url: localhost:7151
    eventUrl: localhost:7153
    grpcOptions:
      ssl-target-name-override: peer1.orgmai.test.com
      keep-alive-time: 0s
      keep-alive-timeout: 50s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: false
    tlsCACerts:
      path: ${GOPATH}/src/github.com/test.com/test/fixtures/crypto-config/peerOrganizations/orgmai.test.com/tlsca/tlsca.orgmai.test.com-cert.pem


certificateAuthorities:
  ca.orgmai.test.com:
    url: http://localhost:7054
    tlsCACerts:
      path: ${GOPATH}/src/github.com/test.com/test/fixtures/crypto-config/peerOrganizations/orgmai.test.com/ca/ca.orgmai.test.com-cert.pem
    registrar:
      enrollId: admin
      enrollSecret: adminpw
    caName: ca.orgmai.test.com




entityMatchers:
  peer:
    - pattern: (\w*)peer0.orgmai.test.com(\w*)
      urlSubstitutionExp: localhost:7051
      eventUrlSubstitutionExp: localhost:7053
      sslTargetOverrideUrlSubstitutionExp: peer0.orgmai.test.com
      mappedHost: peer0.orgmai.test.com

    - pattern: (\w*)peer1.orgmai.test.com(\w*)
      urlSubstitutionExp: localhost:7151
      eventUrlSubstitutionExp: localhost:7153
      sslTargetOverrideUrlSubstitutionExp: peer1.orgmai.test.com
      mappedHost: peer1.orgmai.test.com


  orderer:
    - pattern: (\w*)orderer.test.com(\w*)
      urlSubstitutionExp: localhost:7050
      sslTargetOverrideUrlSubstitutionExp: orderer.test.com
      mappedHost: orderer.test.com

  certificateAuthorities:
    - pattern: (\w*)ca.orgmai.test.com(\w*)
      urlSubstitutionExp: http://localhost:7054
      mappedHost: ca.orgmai.test.com
